### ISSUE TITLE
I am encountering this error. Kindly help me out.

### ISSUE THREAD

**Issue by Sarala1** [AVINASH793/Panoramic-Image-Stitching-using-invariant-features#1]
Traceback (most recent call last):
  File "C:/Users/user/PycharmProjects/Panoramic-Image-Stitching-using-invariant-features-master/panorama.py", line 2, in <module>
    import imutils
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\imutils\__init__.py", line 8, in <module>
    from .convenience import translate
  File "C:\Users\user\PycharmProjects\untitled\venv\lib\site-packages\imutils\convenience.py", line 6, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Process finished with exit code 1

**Comment by AVINASH793** [comment]
Please install OpenCV. If installed then you have to reinstall. It may happen that it has not correctly installed.

**Comment by Sarala1** [comment]
I have installed opencv 3.4.4. But i am not getting. Please help me.

**Comment by AVINASH793** [comment]
@Sarala1  , I have used opencv version 3.3.0.

**Comment by Avinash793** [comment]
@Sarala1 We have updated the repo to use latest libraries as of 2024. You can now give a shot!
